[package]
name = "slack"
version = "0.16.0"
authors = ["Benjamin Elder <bentheelder@gmail.com>", "Matt Jones <mthjones@gmail.com>"]
repository = "https://github.com/slack-rs/slack-rs.git"
documentation = "http://slack-rs.github.io/slack-rs/slack/index.html"
description = "slack realtime messaging client: https://api.slack.com/bot-users"
license = "Apache-2.0"

[dependencies]
reqwest = "0.4.0"
slack_api = { version = "0.16.0", features = ["reqwest"] }
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
tungstenite = "0.1.0"
native-tls = "0.1.1"
